In [2]:
#Numpy stands for Numerical Python
#It is an open source module of Python which provides fast mathematical computation on arrays and matrices. 
import numpy as np
#np is now the imported numpy package

In [3]:
#differences between NumPy arrays and the standard Python sequences:
# NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).
# Changing the size of an ndarray will create a new array and delete the original.
#The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

# NumPy’s main object is the homogeneous multidimensional array. It is a table with same type elements, i.e, integers or string or characters (homogeneous), usually integers. 
# In a NumPy array, the number of dimensions is called the rank, and each dimension is called an axis. 
# So the rows are the first axis, and the columns are the second axis with a rank 2
# For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. 
# That axis has 3 elements in it, so we say it has a length of 3
#getting documentation of any numy function
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [36]:
# NumPy’s array class is called ndarray.
# Attributes of ndarray
import numpy as np
# To create sequences of numbers arrange(start,stop,step) is used
a=np.arange(15).reshape(3,5)
print(a)
print(type(a))
#the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m)
print(a.shape)
#the number of axes (dimensions) of the array.
print(a.ndim)
#the total number of elements of the array. This is equal to the product of the elements of shape
print(a.size)
#an object describing the type of the elements in the array. 
print(a.dtype)
#the size in bytes of each element of the array. 
print(a.itemsize)
#the buffer containing the actual elements of the array. 
print(a.data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
(3, 5)
2
15
int64
8


In [18]:
#Array Creation
import numpy as np
#creating a vector
a=np.array([2,3,4])
print(a)

#creating a matrix 2*3
b=np.array([(1,2,3),(4,5,6)])
b=np.array([[1,2,3],[4,5,6]])
print(b)

# The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[2 3 4]
[[1 2 3]
 [4 5 6]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [39]:
# functions to create arrays with initial placeholder content.
#filled with inital zeroes
a=np.zeros((3,4))
print(a)
#filled with inital ones
b=np.ones((4,3),dtype=np.int16)
print(b)
#filles with uninitailized random values
c=np.empty((2,3))
print(c)
#filles with initailized specified value
d=np.full((3,4),11)
print(d)
#identity matrix creation
e=np.eye(3)
print(e)
#diagonal matrix
f=np.diag(np.array([1,2,3]))
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0.00708532 0.0348209  0.01863363]
 [0.69143149 0.46422209 0.67082615]]
[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [30]:
#When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, 
# due to the finite floating point precision. For this reason, it is usually better to use the function linspace 
# that receives as an argument the number of elements that we want, instead of the step:
# np.linspace(0,2,9) (start,end,no of points)
from numpy import pi
x=np.linspace(0,2*pi,10)
print(x)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [35]:
#generating random values
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
np.random.rand(3,2)
#Return a sample (or samples) from the “standard normal” distribution.
#For random samples from N(\mu, \sigma^2), use:
# sigma * np.random.randn(...) + mu
np.random.randn()
#Two-by-four array of samples from N(3, 6.25):
2.5 * np.random.randn(2, 4) + 3

array([[0.08342544, 0.16351368, 1.78585464, 3.20856352],
       [3.17965976, 0.53570411, 3.03638892, 4.26555626]])

In [41]:
#for reversing a sequence: 
a=np.arange(1,10,2)
print(a)
print(a[::-1])
#A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the originalarrayisnotcopiedinmemory. 
#You can usenp.may_share_memory()to check if two arrays share the same memory block

[1 3 5 7 9]
[9 7 5 3 1]


In [46]:
#computing prime numbers in a give range
start=int(input("Enter start number:"))
end=int(input("Enter end number:"))
length=end-start
is_prime=np.ones((length,),dtype=bool)
N_max=int(np.sqrt(len(is_prime)-1))
for j in range(2,N_max+1):
    is_prime[2*j::j]=False
print(is_prime)

Enter start number:0
Enter end number:10
[ True  True  True  True False  True False  True False False]


In [63]:
#Operations in Numpy
#Elementwise Operations
#with scalars
a=np.array([1,2,3,4])
print(a+1)
print(2**a)
#numerical Operations
b = np.arange( 4 )+1
print(b)
a-b
a*b#not matrix multiplication
a-b
#for matrix multiplication
c=a.dot(b) #or np.dot(a,b)
print(c)
a<3
#Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.
b += a
print(b)

[2 3 4 5]
[ 2  4  8 16]
[1 2 3 4]
30
[2 4 6 8]


In [70]:
#comparisions OPerations
a==b
a>b
np.array_equal(a,b)
#logical Operations
np.logical_or(a,b)
np.logical_and(a,b)
#otheroperations
np.log(15)
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [84]:
#BAsic Reductions
x=np.array([[1,1],[2,2]])
np.sum(x)
x.sum(axis=0)#columns
x.sum(axis=1)#rows
z=np.array([1,2,34,5,6])
print(z.min())
print(z.max())
print(z.argmin())#index of the min element
print(z.argmax())
print(z.mean())
print(np.median(z))
print(z.std())

1
34
0
2
9.6
5.0
12.338557452149743


In [91]:
#shape manipulation
#the following three commands all return a modified array, but do not change the original array:
a = np.floor(10*np.random.random((3,4)))
print(a.ravel())#returns a vector
print(a.reshape(6,2)) # returns the array with a modified shape
a.T# returns the array, transposed
print(a)
#The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:
a.resize((2,6))
print(a)

[1. 5. 2. 7. 7. 3. 6. 9. 1. 9. 5. 1.]
[[1. 5.]
 [2. 7.]
 [7. 3.]
 [6. 9.]
 [1. 9.]
 [5. 1.]]
[[1. 5. 2. 7.]
 [7. 3. 6. 9.]
 [1. 9. 5. 1.]]
[[1. 5. 2. 7. 7. 3.]
 [6. 9. 1. 9. 5. 1.]]


In [94]:
# Basic operations on numpy arrays(addition,etc.) are elementwise 
# Nevertheless,It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the samesize: this conversion is called broadcasting.
#adding a dimension
z=np.array([1,2,3,4,5])
print(z)
z[:, np.newaxis]
print(z)
z[np.newaxis,:]
print(z)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [96]:
a = np.array([[4, 3, 5], [1, 2, 1]]) 
b = np.sort(a, axis=1) #sorting each row separtely
print(b)
a.sort(axis=1)#in-place sorting
print(a)

[[3 4 5]
 [1 1 2]]
[[3 4 5]
 [1 1 2]]


In [100]:
#structured data type
samples = np.zeros((6,), dtype=[('sensor_code', 'S4'),('position', float), ('value', float)])
print(samples)
samples[:] = [('ALFA', 1, 0.37), ('BETA', 1, 0.11), ('TAU', 1, 0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]
print(samples)
print(samples['sensor_code'])
samples[0]

[(b'', 0., 0.) (b'', 0., 0.) (b'', 0., 0.) (b'', 0., 0.) (b'', 0., 0.)
 (b'', 0., 0.)]
[(b'ALFA', 1. , 0.37) (b'BETA', 1. , 0.11) (b'TAU', 1. , 0.13)
 (b'ALFA', 1.5, 0.37) (b'ALFA', 3. , 0.11) (b'TAU', 1.2, 0.13)]
[b'ALFA' b'BETA' b'TAU' b'ALFA' b'ALFA' b'TAU']


(b'ALFA', 1., 0.37)

In [107]:
#polynomials
#3x**2+2*x-1
p=np.poly1d([3,2,-1])
print(p)
print(p(0))
print(p.roots)
print(p.order)
p = np.polynomial.Polynomial([-1, 2, 3]) # coefs in different order! 
print(p.roots())
print(p.degree())

   2
3 x + 2 x - 1
-1
[-1.          0.33333333]
2
[-1.          0.33333333]
2


In [ ]:
#loading datafiles
data = np.loadtxt('data/populations.txt') 
print(data)

In [111]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
print(a.transpose())
print(np.linalg.inv(a))
u = np.eye(2)
print(np.trace(u) ) # trace
y = np.array([[5.], [7.]])
print(np.linalg.solve(a, y))


[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
2.0
[[-3.]
 [ 4.]]


In [112]:
#indices() will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension
np.indices((3,3))
#common valus in x and y
print(np.intersect1d(x,y))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])